### ISSUE TITLE
Crash when swiping all keys

### ISSUE THREAD

**Issue by mioux** [nicolasbrailo/PianOli#10]
If you swipe all keys from left to right, the app crashes

I'm using a Nexus 6 with latest lineageos

Problem is : my daughter do it each time :smile:

**Comment by nicolasbrailo** [comment]
Hi @mioux! Thanks for the report. Unfortunately I can't reproduce the issue (I don't have a nexus 6 though). Any chance you could upload a stacktrace of the problem?

**Comment by mioux** [comment]
I son't know how to get it. When the app crashes, I only have the "Close/restart  app"  options.

I'm downloading android studio to build latest code, and try it

**Comment by mioux** [comment]
Do you know how I can get the stack trace ? I have built the app with debug, I only have "close/restart app" with debug enabled.

My device is rooted (just for f-droid privilege extension :smile:), if it can help

**Comment by nicolasbrailo** [comment]
Hi, @mioux. Thanks for your contribution! Feel free to also submit PR's if you implement new features :)

There are a few simple ways to get a stacktrace. With Android studio you should be able to see a tab that looks like this:

![Logcat](https://developer.android.com/studio/images/debug/logcat_2x.png)
(From https://developer.android.com/studio/debug)

Also, if you're running Linux, the easiest might be:

1. Enable developer mode and usb debug on your phone if not already done (https://developer.android.com/studio/debug/dev-options)
2. Connect your phone
3. Open a terminal and run "adb logcat -c && adb logcat"
4. Reproduce the crash; there should now be a crashlog in the console

This should also work in Windows, assuming you can run adb from a terminal (I can't help with that, though!)

**Comment by mioux** [comment]
Thanks !

Here it is : [PianOli_logcat.log](https://github.com/nicolasbrailo/PianOli/files/2985632/PianOli_logcat.log)

**Comment by nicolasbrailo** [comment]
That's great. The stacktrace makes this very easy: The problem is due to a regression I introduced in e5d052 so it should be a trivial fix. I'll release a new version over the weekend.

Thanks for the report!

**Comment by mioux** [comment]
Tested and aproved, thanks :+1:

**Comment by nicolasbrailo** [comment]
Thank you for the report! I expect to release a new version in F-Droid with this fix, soon.
