### ISSUE TITLE
Add exit instructions to F-Droid & Readme

### ISSUE THREAD

**Issue by annihat** [nicolasbrailo/PianOli#21]
Hi, 
the descriptions on F-Droid & in the Github readme seem to suggest there's no way to exit the app, this is worrying.

Can you add a line about exiting the app, please?

**Comment by pserwylo** [comment]
Good call. I think it would be good to move the description from F-Droid into the `./fastlane/` directory in this repo now that it is responsible for screnshots. That way it is easier to make changes (no need to make merge requests to fdroiddata and bother the contributors there). I'll see if I can get around to this some time.
