### ISSUE TITLE
Increase brightness when pressing coloured keys

### ISSUE THREAD

**Issue by pserwylo** [nicolasbrailo/PianOli#23]
Now my kid is getting older, she is playing with this more. Often, she just randomly mashes buttons. But when she *does* intentionally move her finger on a single key and press it repeadetly, it is always the black key. My hypothesis is because they change to a substantially brighter shade when pressed:

![image](https://user-images.githubusercontent.com/248565/114641948-5670b380-9d16-11eb-9e9b-805e4c543300.png)

Compared to the coloured keys which go darker (below the blue key is pressed:

![image](https://user-images.githubusercontent.com/248565/114642019-799b6300-9d16-11eb-9609-6ed95e84746b.png)

Mind if I send a pull request through which lightens the keys much more when pressed, so it is more obvious when they are pressed? If you like we can play test it with my bubba first to confirm my hypothesis before sending the request.

**Comment by nicolasbrailo** [comment]
@pserwylo sounds like a great idea!
