### ISSUE TITLE
Broken keys

### ISSUE THREAD

**Issue by Ysurgeon13** [nicolasbrailo/PianOli#27]
The upper F note (the green one) makes a "thunk" sound and the upper A (red) and B (orange) are silent. Running LineageOS on a Samsung Galaxy s9.

**Comment by nicolasbrailo** [comment]
@Ysurgeon13 thanks for the report. The thunk sound is used whenever the sound file couldn't be loaded.

1. I assume all other notes play correctly in your case. Is that true?
2. Does the problem go away if you select a new sound set? (ie change from piano to guitar)
3. What app version are you using?
4. Do you know what your resolution is?

Thanks again for the report!

**Comment by Ysurgeon13** [comment]
1. All the notes from the lowest through the upper Aflat work perfectly except the upper F. Any notes (there are A, Bflat, and B) higher than Aflat, are silent. 
2. It's like that on all the sound sets. 
3. Version 1.12
4. Documentation says 1440 x 2960 Pixels

Thanks for the awesome simple app! My 6-month-old loves it!

**Comment by MrReSc** [comment]
I have exactly the same problem as @Ysurgeon13.

**Comment by nicolasbrailo** [comment]
Well, this is embarrassing.

1. Re the thunk sound for the A: there was a bug in the notes definition (ie at some point in the scale I skipped a note, and the A was mapped to the spot without a key between mi and fa). This should be fixed now and will land in fdroid in a week or two.

2. Re high notes not working: there is no smart sound generator in this app, the notes are simple sound assets. There are enough sounds for two full scales, but for some reason the last 3 keys were not mapped. I added this mapping now, so you should get some extra sounds. Having said that: notes higher than two full scales have no mapping, so they'll still be silent. To add these notes we'd need to extend the sound assets or use a better approach to sound generation, and I'm afraid I won't have time to support either of these any time soon. (two full scales should be enough for everyone though, right!?)

**Comment by pserwylo** [comment]
How about we ensure that no more than two full scales are shown, by: making the keys wider if there would have been a need for it, or showing black bars on either side. I think the first would work best, because I can't think of a device which would have an aspect ratio such that this would look weird. Sure, if it was a very very wide, and very very short device, each key would look very fat, but that seems unlikely. Probably more likely that devices with high DPI want to show many keys, because they are not a percentage but rather a fixed size.

**Comment by nicolasbrailo** [comment]
Not displaying keys that wouldn't have sound sounds like a brilliant idea!

**Comment by Ysurgeon13** [comment]
Update works perfectly!! Thanks so much for the fix and the speedy response! :0D
