### ISSUE TITLE
settings accidentaly launched

### ISSUE THREAD

**Issue by mus1c-123** [nicolasbrailo/PianOli#32]
I had a 1 year old play the app and she triggered settings every 10 sec by placing her whole hand on the keyboard. Can there be an update to only launch setting if the last 2 ⚙️ keys are pressed and are the only ones pressed?

**Comment by fabykr** [comment]
10 month old baby, same problem :-)

**Comment by Magneticdud** [comment]
the baby also right now wants to try each key with each finger, so it will be easy to open settings. Settings should open only if the two keys with gears are pressed, if other 8 keys are pressed at the same time, it should ignore
