### ISSUE TITLE
Bug: multi-touch drag doesn't always release keys (incl. steps to reproduce)

### ISSUE THREAD

**Issue by juleskers** [nicolasbrailo/PianOli#40]
First off: thank you for making PianOli, it's great entertainment for my 13-month-old daughter! :orange_heart: 

I've found that keys sometimes stay "stuck" in pressed/highlighted mode, and after a few days of experimentation, can now reproduce it, enabling a proper bug report :-)

Since "stuck" keys also work for entering the config menu, I believe this is part of #12, because it's too easy to enter config with stuck keys.

**Sequence to reproduce**

  1. touch *and hold* any key ("key 1", a note plays)
  2. touch and hold any second key ("key 2", not the same, that note plays too)
  3. *drag* your second finger from key 2 to a third key (key 3, key 2 remains pressed/stuck)
  4. release your second finger (key 3 note only now plays, key 3 releases as normal)
  5. release your first finger/key 1.

If you release key 1 *before* key 2, or attempt to drag key 1, no keys become stuck, so it seems the first touch is treated differently than multi-touches.

I could reproduce this on both a Samsung tablet (stock Samsung, android-11) and my Fairphone 3 (custom rom, [E/OS 0.23](https://e.foundation/e-os/), based on LineageOS, android-9).

If I've left anything unclear, or you need additional information, please don't hesitate to ask, I hope I can help you make PianOli even better. :smile: 

Once again, thank you for making this app!

**Comment by pserwylo** [comment]
Oh you are a legend. I've seen this a lot but have not been able to reproduce as you have. Can confirm that your instructions reproduce correctly for me too.

**Comment by juleskers** [comment]
Thanks 😊
The reproduction involved lots of careful observation of my daughter as she was merrily bap-bap-bapping my phone 😄
She keeps discovering things on hardware I've owned for multiple years 😳

**Comment by nicolasbrailo** [comment]
Wow. That's an impressive discovery. I had noticed this weird behaviour too
before, but I could never really spot a pattern. Amazing, thanks for the
detailed repro guide!

In theory, the move-to-another-key behaviour should be handled here:
https://github.com/nicolasbrailo/PianOli/blob/master/app/src/main/java/com/nicobrailo/pianoli/PianoCanvas.java#L292
Since this bug exists, I'm guessing that piece of code doesn't do what I
think it should. With the steps in this bug report it should now be a
question of adding enough printf's to find out how this behaves, and move
the case labels around accordingly.

Thanks again Jules!

**Comment by juleskers** [comment]
Update, because my daughter still enjoys Pianoli.
(I'm a java-dev by day, so I can actually read this stuff, even though I've never touched android development.)

I think I've identified the problem:  
- `ACTION_MOVE` is not like the other `ACTION`s, in that it contains _multiple_ pointers.
- getActionIndex "doesn't apply", so our "calculate `ptr_id`+`key_idx` once before the switch" is an invalid optimisation.

from: [android developers: Handle multi-touch gestures](https://developer.android.com/develop/ui/views/touch-and-input/gestures/multi) > **Track multiple pointers**
> for example, when processing [ACTION_MOVE](https://developer.android.com/reference/android/view/MotionEvent#ACTION_MOVE) event, you can find the index for each cached active pointer ID, retrieve the pointer's coordinates by using the relavent functions ([getX()](https://developer.android.com/reference/android/view/MotionEvent#getX(int)), [getY()](https://developer.android.com/reference/android/view/MotionEvent#getY(int)), etc.), then compare with your cached coordinates to discover the actually moved pointers. There can be multiple moved pointers in one [ACTION_MOVE](https://developer.android.com/reference/android/view/MotionEvent#ACTION_MOVE) event.
> The [getActionIndex()](https://developer.android.com/reference/androidx/core/view/MotionEventCompat#getActionIndex(android.view.MotionEvent)) function does not apply to the [ACTION_MOVE](https://developer.android.com/reference/android/view/MotionEvent#ACTION_MOVE) event.


So the [current code](https://github.com/nicolasbrailo/PianOli/blob/43e28dd/app/src/main/java/com/nicobrailo/pianoli/PianoCanvas.java#L292) is making incorrect assumptions in line 269-273, where it's pre-calculating the `ptr_id` and `key_idx` only once, _before_ we know if it's an action-move.

-----

my _guess_ at what's currently happening is that,
1. since "`getActionIndex` doesn't apply" for `ACTION_MOVE`, it's _probably_ returning a dummy value of `0`,
2. which (though unspecified) happens to map to the "first" touch (ACTION_DOWN) ("_key 1_" in my previous repro-steps)
3. which hasn't moved in _this_ scenario, so..
4. is skipped by line 300: `if (touch_pointer_to_keys.get(ptr_id) != key_idx) {`

-----

**To fix it**, it seems we would need to do a whole lot more work in `case MotionEvent.ACTION_MOVE`
- since `getActionIndex()` doesn't apply, we must check _each_ index
  - I didn't find any nice stream API, so it'll be a for each [`MotionEvent.getPointerCount()`](https://developer.android.com/reference/android/view/MotionEvent#getPointerCount()) index
  - the ever-excellent Vogella has a [tutorial with multi-touch move snippet](https://www.vogella.com/tutorials/AndroidTouch/article.html#exercise-multitouch):
    ```java
        case MotionEvent.ACTION_MOVE: { // a pointer was moved
            for (int size = event.getPointerCount(), i = 0; i < size; i++) {
                PointF point = mActivePointers.get(event.getPointerId(i));
                if (point != null) {
                    point.x = event.getX(i);
                    point.y = event.getY(i);
                }
            }
            break;
        }
    ```
- .. recalculate `ptr_id`+`key_idx` for _that_ index
- .. compare that per-index id+key against the previous `touch_pointer_to_keys` value

----

sketching that out in rough pseudo-code
(disclaimer: it's past midnight, and I don't have an IDE, nor android experience)

```java
case MotionEvent.ACTION_MOVE: {
  // action_move is special, `getActionIndex` value is invalid, we must actually check _each_ pointer by hand.
  // https://developer.android.com/develop/ui/views/touch-and-input/gestures/multi
  for (int size = event.getPointerCount(), i = 0; i < size; i++) {
    final int moved_ptr_id = event.getPointerId(i);  // cf precalc'd ptr_id above switch
    final int moved_key_idx = piano.pos_to_key_idx(
                event.getX(i),
                event.getY(i));

    if (!touch_pointer_to_keys.containsKey(moved_ptr_id)) {
      ..  // log error as before
    }
   // check if key changed
   if (touch_pointer_to_keys.get(moved_ptr_id) != moved_key_idx) {
     .. // key_up > map.put > key_down as before
   }
   
  }
  return true;
```
