### ISSUE TITLE
Overview of additional colour themes (support?)

### ISSUE THREAD

**Issue by juleskers** [nicolasbrailo/PianOli#57]
Hi again!
Much like @pserwylo, the arrival of a new baby in the house rekindled my interest in PianOli. (Congrats @pserwylo !)

I was happy to see all the activity, nice to see it's still going strong!
(the song player is very impressive)

One of the things that caught me out was the change of colour-scheme in #53 .
I agree that it's always better to follow "the" standard if there is one, but as the cynical saying goes "_the nice thing about standards is that there are so many to choose from_".

Personally, I'd never heard of "Boomwhackers", and had to search duckduckgo for them.  
To my layman's understanding, they seem to be rather USA-centric, rather than "international" as mentioned in the original PR.
Then again, there seems to be some software that supports it, and it doesn't hurt.

Again personally, I do miss the cheery brightness of the original rainbow. 

I'm opening this issue not as critique, but as a collection bucket for possible alternate standards, since the original MR mentioned the possibility of theme-switching.
 I'm aware of _at least_ one other variant, and an image search shows many different palettes.  
Perhaps other people know of more colour schemes?

# minimusiker 
In Germany, there is the "Minimusiker" convention, by a children-oriented band/musik-education team.  
This is a rainbow-like scheme, with a red C-note, .  

- They do sell lesson plans using this colour scheme:
  ![image](https://github.com/nicolasbrailo/PianOli/assets/7068025/301defa0-768b-4819-91c6-69a4b8287cce)  
  source: https://minimusiker.de/shop/Materialpaket-4-p253644213
  - note that the xylophone on the top-left corner has white C's, because they're not used in this rendition of "are you sleeping, brother John", the top-right shows the red C's.

I'm not sure how "big" that is in classrooms, or internationally, but they are at least somewhat influential in Germany among the general public.
- They partner with the (immensely popular, available in every children store) "[TonieBox](https://us.tonies.com/pages/toniebox)" music player, of which I (of course..) have one at home. 
- There are [mini-musiker-partnered xylophones](https://www.spiegelburg-shop.de/mein-allererstes-glockenspiel/63603) available in most bookstores, including [at Thalia](https://www.thalia.de/shop/home/artikeldetails/A1057907205) (the "has multiple shops in literally every German city" bookstore).
  - https://www.thalia.de/shop/home/artikeldetails/A1057907205
  - annoyingly, these use a _different_ colour scheme, with a _blue_ C, and adds in white for B. Because why keep your own standards...
    ![image](https://github.com/nicolasbrailo/PianOli/assets/7068025/ae5caf24-baac-4ec4-9dbb-7333c9b4090c)
  - this of course speaks against it being an actual standard.

**Comment by pserwylo** [comment]
Thanks for the feedback @juleskers and congrats. 

I think I'll have a crack at trying to get themes working. At the very least we can then have an ebony + ivory theme and a coloured theme. But if that is easy enough to implement, then it should also be simple to then add subsequent themes too. I'll post back here if I make any progress.

**Comment by pserwylo** [comment]
So far so good. I'll tidy up the code and get a PR for just Boomwhacker + Ebody & Ivory as a first stage, then cut a release. Once out, I'll then add some others as per your recommendations above. (It is a bit selfish, but I find that more, smaller releases means hitting the front page of F-Droid more often, which leads to more people using the app and engaging with us here).

## Settings page

![image](https://github.com/nicolasbrailo/PianOli/assets/248565/87e83ff5-0ebe-4154-aaad-a95f15055d0e)

## Choosing a theme

![image](https://github.com/nicolasbrailo/PianOli/assets/248565/2a8899dd-7256-4160-b534-36efd806ef57)

## Ebony & Ivory theme

![image](https://github.com/nicolasbrailo/PianOli/assets/248565/e4266a6d-2d9e-4c8b-b527-9d5c40bf2120)

**Comment by juleskers** [comment]
Wow, very nice!
Just shows that someone who is familiar with the code can do the work of a dozen newcomers in a fraction of the time ❤️

Frequent, small releases are "totally agile"! No need to be ashamed of that.
also, in the sciences where I once worked, that's called "salami tactic", many small publications are better for your research group than one big splash.

Also, I was in the toybstore today, and did research for the German Market.

When I summarizer, it seems we commonly have
- rainbow (red C) 
- rainbow (blue C) 
- pastel
- wild grab bag for everything with less than a full octave (probably not even tuned) 

-------

Wall of pictures (sorry, no idea to put those in a collapsible box on mobile 😟) 
![IMG_20230831_155138](https://github.com/nicolasbrailo/PianOli/assets/7068025/40c9dfa4-d1f3-4c34-80ce-63bfa4ae6d25)
![IMG_20230831_155108](https://github.com/nicolasbrailo/PianOli/assets/7068025/d0e9f014-0639-4012-93a9-8fa8d2ee2f92)
![IMG_20230831_155157](https://github.com/nicolasbrailo/PianOli/assets/7068025/12033b7d-37b5-41c3-9160-89e26baded29)
![IMG_20230831_155037](https://github.com/nicolasbrailo/PianOli/assets/7068025/ea54c071-2492-4f24-9dcb-fb29b2cd450c)

**Comment by pserwylo** [comment]
Ha, thanks for the market research @juleskers. I've cut a release with black and white / boomwhacker (https://github.com/nicolasbrailo/PianOli/releases/tag/V1.21). Will add a few others in the next few nights as time permits. Might take a few days to a week for F-Droid to build and release. Will only close this issue after implementing a couple of other themes to flesh it out a little bit.

In the future, I'd love to have the "Theme selector" be a list where each list item is actually a mini keyboard with the appropriate colours. An initial investigation last night led me to believe that is much more difficult than I expected, so will hold off on that until we at least have a few themes available. Might create a separate issue for that.

**Comment by juleskers** [comment]
For the theme selector: might it be an idea to make this a whole separate sub-screen?
Then we could use a "full screen" list, using a normal radio button + text label approach.
If I'm not mistaken, the text labels could have inline images. 

A subscreen probably also makes sense for the song-selection, once we expand our choices there.

**Comment by juleskers** [comment]
I've extracted the RGB values for some of the palletes.  
I used gimp, blurred large regions of the picture (to get the average), and then selected the resulting average color with the eyedropper

- pastel (left to right)
  - pistache: 162, 182, 176
  - beige: 158, 148, 142
  - sand: 222, 191, 144
  - dun: 177, 128, 68
  - light pink: 213, 169, 179
  - dark pink: 195, 109, 117
  - plum: 151, 80, 87
-  Rainbow ("Klopfbank", blue to red)
   - dark blue: 5, 29, 120
   - light blue: 10, 109, 179
   - dark green: 71, 138, 37
   - light green: 133, 157, 48
   - yellow: 173, 134, 8
   - light orange: 193, 95, 15
   - dark orange: 189, 86, 22
   - red: 145, 22, 23

**Comment by pserwylo** [comment]
Awesome. Shall I make a file a PR with these two themes? Or are you working on that @juleskers?

**Comment by juleskers** [comment]
Go ahead on a theme PR, I'm not doing anything in that direction right now.
(rather doing German translation, which is slow because I have to tripple check all the grammar as a non-native) 

I'll probably slow down a little, now that my parental leave is over, and I have $DAYJOB again.

**Comment by pserwylo** [comment]
So far so good. But perhaps a little dark. Might try to increase the brightness of each a little bit:

## Rainbow

![image](https://github.com/nicolasbrailo/PianOli/assets/248565/157f1623-9e4b-46ac-89c0-7b03a1b768ef)

## Pastel

![image](https://github.com/nicolasbrailo/PianOli/assets/248565/91101b4b-e7cd-4be8-86a9-9f26a0a1a92a)

Thoughts @juleskers?

**Comment by juleskers** [comment]
Ooh, nice!

I agree they're both too dark.
I think that's a common side effect of using the eyedropper on real-life pictures.

**Comment by pserwylo** [comment]
Rainbow looks better with misc increase to of contrast and brightness via gimp. Just picked a value which didn't go too far:

![image](https://github.com/nicolasbrailo/PianOli/assets/248565/010cbeb1-600e-4276-9b94-c8a526073c78)

Pastel here:

![image](https://github.com/nicolasbrailo/PianOli/assets/248565/a43f81ae-22d2-4f4a-83e7-3fe6ef1c16b4)

Think I'm pretty happy with them. Will try to cut a release with these, but happy to amend if you have any improvement suggestions.

**Comment by juleskers** [comment]
I like how cheery rainbow is now!
one thing I am "worried" about, after the brightness increase, the two oranges look virtually identical (at least on my phone screen)
I'd make the dark-orange a tad more reddish and/or darker. Light-orange can't change too much, or it will become too close to the yellow next to it. 
(Did you know there's entire research groups dedicated to the topic of subjective observed colour difference?) 


As for pastel: I love the middle (sand - plum) but the pistache-green and gray look a tad too desaturated to me.
That's sort of the point of pastel, but it's going a bit too far into "grayscale" for my tastes.

**Comment by pserwylo** [comment]
Cool, good points. Here is a slightly tweaked rainbow:

![image](https://github.com/nicolasbrailo/PianOli/assets/248565/21f27ea9-005b-4285-8b22-cea0393cc7ef)

As for colour theory, yes, colorbrewer2 was my go-to for producing charts during my PhD. Love it.

not quite sure what to do with the pastel themes. How about we just pick one of the qualitative sets from colorbrewer and be done with it? e.g. https://colorbrewer2.org/#type=qualitative&scheme=Pastel1&n=8 ?

**Comment by juleskers** [comment]
I think the rainbow is perfect after your tweaks.
For a children's game, I think we should prioritise "happy" over "scientifically useful" 😉
Alternatively, we could always dig out the "classic" rainbow from before Boomwhacker out of the git history.. (why does this only occur to me now 🤦)

The colorbrewer pastel suggestion looks way better (both more "happy" and more distinct) than my eyedropper results. Let's go with that one!
