### ISSUE TITLE
One key does not play.

### ISSUE THREAD

**Issue by a-raccoon** [nicolasbrailo/PianOli#6]
There will always be one key that doesn't play a tune. Invariably, it's the last key to be first-pressed when the app was first launched. Kill the app and a different key won't work if it was neglected.

This feature helps prepare babies for the real world when they eventually visit their aunt's house.

**Comment by nicolasbrailo** [comment]
Ooooohh nice! I noticed a few times keys stopped working but I was never able to find a pattern. I see now that the last 3 keys to be pressed won't have sound. Awesome find, thanks!

> This feature helps prepare babies for the real world when they eventually visit their aunt's house.
HAHAHAHAHA that's brilliant!
